import os

try:
    import matplotlib
    matplotlib.use('Agg') # Headless
    import matplotlib.pyplot as plt
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
except ImportError:
    plt = None
    canvas = None

class PDFExporter:
    def __init__(self, export_dir):
        self.export_dir = export_dir
        self.graphs_dir = os.path.join(export_dir, "graphs")
        os.makedirs(self.graphs_dir, exist_ok=True)

    def export_pdf(self, telemetry):
        path = os.path.join(self.export_dir, "report.pdf")
        if not canvas:
            # Fallback if reportlab failed to install
            with open(path, "w") as f:
                f.write("PDF Generation failed due to missing ReportLab dependency.")
            return
            
        c = canvas.Canvas(path, pagesize=letter)
        c.drawString(100, 750, "CellWatch Offline Analysis Report")
        c.drawString(100, 730, "Generated by Python ReportLab")
        
        # Plot FPS
        if plt and telemetry:
            fps_data = [t.get("fps", 0) for t in telemetry]
            plt.figure(figsize=(6, 4))
            plt.plot(fps_data, label="FPS", color='blue')
            plt.title("Pipeline FPS")
            plt.xlabel("Frame")
            plt.ylabel("FPS")
            plt.legend()
            chart_path = os.path.join(self.graphs_dir, "fps.png")
            plt.savefig(chart_path)
            plt.close()
            
            c.drawImage(chart_path, 100, 400, width=400, height=300)
            
        c.save()
